CREATE TABLE Wardens (
    staff_number NVARCHAR(50) NOT NULL PRIMARY KEY,
    first_name NVARCHAR(100) NOT NULL,
    surname NVARCHAR(100) NOT NULL,
    location NVARCHAR(100) NOT NULL,
    created_at DATETIME2 NOT NULL CONSTRAINT DF_Wardens_CreatedAt DEFAULT (SYSUTCDATETIME()),
    last_updated DATETIME2 NOT NULL CONSTRAINT DF_Wardens_LastUpdated DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT CK_Wardens_Location CHECK (location IN (
        'Alwyn Hall',
        'Beech Glade',
        'Bowers Building',
        'Burma Road Student Village',
        'Centre for Sport',
        'Chapel',
        'The Cottage',
        'Fred Wheeler Building',
        'Herbert Jarman Building',
        'Holm Lodge',
        'Kenneth Kettle Building',
        'King Alfred Centre',
        'Martial Rose Library',
        'Masters Lodge',
        'Medecroft',
        'Medecroft Annexe',
        'Paul Chamberlain Building',
        'Queen’s Road Student Village',
        'St Alphege',
        'St Edburga',
        'St Elizabeth’s Hall',
        'St Grimbald’s Court',
        'St James’ Hall',
        'St Swithun’s Lodge',
        'The Stripe',
        'Business School',
        'Tom Atkinson Building',
        'West Downs Centre',
        'West Downs Student Village',
        'Winton Building',
        'Students’ Union'
    ))
);
